export const COUNTRIES = [
    { label: "USA", value: "USA" },
    { label: "Canada", value: "CANADA" },
    { label: "United Kingdom", value: "UNITED_KINGDOM" },
    { label: "France", value: "FRANCE" },
    { label: "Italy", value: "ITALY" },
    { label: "Spain", value: "SPAIN" },
    { label: "Germany", value: "GERMANY" },
    { label: "Netherlands", value: "NETHERLANDS" },
    { label: "Switzerland", value: "SWITZERLAND" },
    { label: "Australia", value: "AUSTRALIA" },
    { label: "New Zealand", value: "NEW_ZEALAND" },
    { label: "Japan", value: "JAPAN" },
    { label: "South Korea", value: "SOUTH_KOREA" },
    { label: "Thailand", value: "THAILAND" },
    { label: "Singapore", value: "SINGAPORE" },
    { label: "Malaysia", value: "MALAYSIA" },
    { label: "UAE", value: "UAE" },
    { label: "Turkey", value: "TURKEY" },
    { label: "Indonesia", value: "INDONESIA" },
    { label: "Maldives", value: "MALDIVES" },
    { label: "India", value: "INDIA" },
    { label: "China", value: "CHINA" },
    { label: "Vietnam", value: "VIETNAM" },
    { label: "Philippines", value: "PHILIPPINES" },
    { label: "Egypt", value: "EGYPT" },
    { label: "Brazil", value: "BRAZIL" },
    { label: "South Africa", value: "SOUTH_AFRICA" },
    { label: "Mexico", value: "MEXICO" },
    { label: "Portugal", value: "PORTUGAL" },
    { label: "Greece", value: "GREECE" },
];
